package:
  name: pyvar
  version: 0.0.2

source:
  path: ..

requirements:
  build:
    - python
    - numpy 

  run:
    - pandas
    - numpy
    - scipy
    - statsmodels
    - sympy
    - matplotlib
    - tornado
